# Site
name: 'AI Product Strategist'
title: 'AI Product Strategist'
description: 'Navigate AI in product management with our expert guides and tips. Stay informed on the latest innovations to boost your product success.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'ai-product-strategist'
email: 'contact@aiproductstrategist.com'
mailchimp-list: 'https://aiproductstrategist.us20.list-manage.com/subscribe/post?u=1843c75170534ac1627a4ee20&amp;id=5d9c5d2ddb&amp;f_id=002147e0f0'
url: 'https://aiproductstrategist.com'
include: ["_pages"]
permalink: /:title/

theme: focus-theme

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: alex_thorpe
      avatar: /assets/images/avatar1.jpg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]